
services:
  
  mysql:
    image: mysql:5.7
    container_name: mysql_db_MYSQLConnection
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
      MYSQL_USER: dbUser
      MYSQL_PASSWORD: dbPassword
    ports:
      - 3308:3306
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql

    labels:
      - "description=Container for MySQL database to test MySQLSSHConnection class in rentasad.library.db package"

volumes:
  mysql_data:
    driver: local
